<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="css/carrefy.css"> 
    <title>Carrefy</title>
</head>
<header>
    <a href="<?=BASE_URL?>home"> <img id="logo" src="img/CarrefyLogo.png" alt="carrefylogo"> </a>
</header>

<nav>
    <a href="<?=BASE_URL?>login">Acceder como administrador</a></li>
</nav>

<body>
 <main>